---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

#params:
#  ATTENDEE_SERVICE_URL:

inputs:
- name: moviefun-source

run:
  path: moviefun-source/ci/tasks/smoke-test.sh
